INSERT INTO movie (title, rating, cast, director, genre, release_date, running_time, language, synopsis,poster_link)
VALUES ('Oppenheimer', 9.4, 'Cillian Murphy, Emily Blunt, Matt Damon', 'Christopher Nolan', 'Documentary, History', '2023-07-20', 150, 'English', "During World War II, Lt. Gen. Leslie Groves Jr. appoints physicist J. Robert Oppenheimer to work on the top-secret Manhattan Project. Oppenheimer and a team of scientists spend years developing and designing the atomic bomb. Their work comes to fruition on July 16, 1945, as they witness the world's first nuclear explosion, forever changing the course of history.","https://i.ibb.co/ZKtCs16/oppenheimer-poster.jpg" );
VALUES ('Barbie', 8, 'Margot Robbie, Ryan Ghosling, Will Ferrel', 'Greta Gerwig', 'Animation, Comedy', '2023-07-20', 114, 'English', "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.","https://i.ibb.co/4KxmQwX/barbie-poster.jpg");
VALUES ('SAW', 7.5, 'Tobin Bell, Shawnee Smith, Renata Vaca', 'Kevin Greutert', 'Horror, Drama', '2023-10-19', 118, 'English', "Hoping for a miraculous cure, John Kramer travels to Mexico for a risky and experimental medical procedure, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer uses deranged and ingenious traps to turn the tables on the con artists.","https://i.ibb.co/FzMHQ4c/saw-poster.jpg");
VALUES ('Avatar', 9.5, 'Sam Worthington, Zoe Saldana, Sigourney Weaver', 'James Cameron', 'Action, Adventure, Fantasy', '2009-12-18', 162, 'English', "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. Jake Sully (Sam Worthington), a paralyzed former Marine, becomes mobile again through one such Avatar and falls in love with a Na'vi woman (Zoe Saldana). As a bond with her grows, he is drawn into a battle for the survival of her world.", 'https://i.ibb.co/vhqB1nN/avatar-poster.jpg');
VALUES ('Transformers', 7.8, 'Shia LaBeouf, Megan Fox, Josh Duhamel', 'Michael Bay', 'Action, Sci-Fi', '2007-07-03', 144, 'English', "The fate of humanity is at stake when two races of robots, the good Autobots and the villainous Decepticons, bring their war to Earth. The robots have the ability to change into different mechanical objects as they seek the key to ultimate power. Only a human youth, Sam Witwicky (Shia LaBeouf) can save the world from total destruction.", 'https://i.ibb.co/6YcNCqr/transformer-2007.jpg');
VALUES ('Home Alone', 8.5, 'Macaulay Culkin, Joe Pesci, Daniel Stern', 'Chris Columbus', 'Comedy, Family', '1990-11-16', 103, 'English',"When bratty 8-year-old Kevin McCallister (Macaulay Culkin) acts out the night before a family trip to Paris, his mother (Catherine O'Hara) makes him sleep in the attic. After the McCallisters mistakenly leave for the airport without Kevin, he awakens to an empty house and assumes his wish to have no family has come true. But his excitement sours when he realizes that two con men (Joe Pesci, Daniel Stern) plan to rob the McCallister residence, and that he alone must protect the family home.", 'https://i.ibb.co/2YQrc4X/home-alone-poster.jpg');
VALUES ('The Godfather', 9.9, 'Marlon Brando, Al Pacino, James Caan', 'Francis Ford Coppola', 'Crime, Drama', '1972-03-24', 175, 'English', "Widely regarded as one of the greatest films of all time, this mob drama, based on Mario Puzo's novel of the same name, focuses on the powerful Italian-American crime family of Don Vito Corleone (Marlon Brando). When the don's youngest son, Michael (Al Pacino), reluctantly joins the Mafia, he becomes involved in the inevitable cycle of violence and betrayal. Although Michael tries to maintain a normal relationship with his wife, Kay (Diane Keaton), he is drawn deeper into the family business.", 'https://i.ibb.co/Ttyrpv5/godfather-poster.jpg');
VALUES ('The Shawshank Redemption', 9.7, 'Tim Robbins, Morgan Freeman, Bob Gunton', 'Frank Darabont', 'Drama', '1994-09-23', 142, 'English', "Andy Dufresne (Tim Robbins) is sentenced to two consecutive life terms in prison for the murders of his wife and her lover and is sentenced to a tough prison. However, only Andy knows he didn't commit the crimes. While there, he forms a friendship with Red (Morgan Freeman), experiences brutality of prison life, adapts, helps the warden, etc., all in 19 years.", 'https://i.ibb.co/wK1vCVv/shawshank-redemption-poster.jpg');
